import { Space,  Typography} from 'antd';
import { DribbbleSquareOutlined } from '@ant-design/icons';
import React from "react";
const { Title } = Typography;
const AboutPage = () => (
  <Space size="large" direction="vertical">
    <section>
      <Title>About Mastermind Game  <DribbbleSquareOutlined /></Title>
      <p>This is a game where you will try to guess a 4-digit combination that is randomly generated by our application.</p>
    </section>      
  </Space>
);

export default AboutPage;